# Generated by Django 2.1.1 on 2019-02-20 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ans',
        ),
    ]
