# Generated by Django 2.1.1 on 2019-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmembership',
            name='name',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='count',
            field=models.IntegerField(default=0, verbose_name='题目数'),
        ),
    ]
