# Generated by Django 2.1.1 on 2019-03-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='members',
            field=models.ManyToManyField(null=True, through='android.QuestionMembership', to='android.Question'),
        ),
    ]
