# Generated by Django 2.1.1 on 2019-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetips',
            name='type',
            field=models.CharField(choices=[('txt', 'text'), ('img', 'image'), ('null', 'null')], max_length=10,
                                   verbose_name='类型'),
        ),
    ]
