# Generated by Django 2.1.1 on 2019-03-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('android', '0002_auto_20190324_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='members',
            field=models.ManyToManyField(through='android.QuestionMembership', to='android.Question'),
        ),
    ]
