# Generated by Django 2.1.1 on 2018-10-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180930_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile_photo',
            field=models.ImageField(default='img/default_handsome.jpg', upload_to='store/img', verbose_name='头像'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'student_id')},
        ),
    ]
