# Generated by Django 2.1.1 on 2018-10-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181001_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '管理员'), ('user', '用户')], default='user', max_length=128, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_photo',
            field=models.ImageField(default='img/default_handsome.jpg', upload_to='img/profile_photo/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='学号'),
        ),
    ]
