# Generated by Django 2.1.1 on 2018-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181003_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='未知', max_length=256, verbose_name='学院'),
        ),
    ]
