# Generated by Django 2.1.1 on 2019-01-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '用户')], default='user', max_length=128, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', 'male'), ('女', 'female')], default='female', max_length=32, verbose_name='性别'),
        ),
    ]
