# Generated by Django 2.1.1 on 2019-02-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0006_auto_20190126_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='分组名')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('invite_reason', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_photo',
            field=models.FileField(default='img/default_handsome.jpg', upload_to='store/upload/%Y/%m/%d',
                                   verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='login.Membership', to='login.User'),
        ),
    ]
